message(STATUS "    [[ Detecting MPI.... ]] ")

if(MINGW)
	message( STATUS "In MINGW" )
	set(MPI_FOUND OFF)
	set(MPI_PATH "C:/Program Files (x86)/Microsoft SDKs/MPI")
	if(IS_DIRECTORY "${MPI_PATH}")
		message( STATUS "found ${MPI_PATH}" )
		set(MPI_FOUND ON)
                set(MPI_C_INCLUDE_DIRS "${MPI_PATH}/Include")
	else()
		message( STATUS "no ${MPI_PATH}" )
	endif()
else()
	find_package(MPI)
endif()

